version: '3.9'
services:
  api:
    build: .
    container_name: base-api
    environment:
      - NODE_ENV=development
      - PORT=3000
    ports:
      - '3000:3000'
    volumes:
      - ./.env:/app/.env:ro
    command: ["node", "dist/main.js"]
